### ISSUE TITLE
Doesn't work after Deploying

### ISSUE THREAD

**Issue by arudmin** [UnlyEd/n8n-heroku-demo#2]
Mar 18 01:32:17 n8ntestapp heroku/web.1 Starting process with command /start.sh
Mar 18 01:32:19 n8ntestapp app/web.1 N8N will start on '34387'
Mar 18 01:32:19 n8ntestapp app/web.1 postgres://qqq:aaa@ec2-54-247-70-127.eu-west-1.compute.amazonaws.com:5432/ccc
Mar 18 01:32:19 n8ntestapp app/web.1 postgre config detected
Mar 18 01:32:19 n8ntestapp app/web.1 postgres://qqq:aaa@ec2-54-247-70-127.eu-west-1.compute.amazonaws.com:5432/ccc
Mar 18 01:32:19 n8ntestapp app/web.1 indentified DB in use postgreSQL
Mar 18 01:32:21 n8ntestapp app/web.1 UserSettings got generated and saved to: /data/.n8n/config
Mar 18 01:32:21 n8ntestapp app/web.1 (node:14) UnhandledPromiseRejectionWarning: error: no pg_hba.conf entry for host "3.249.185.149", user "usr", database "dbdbdb", SSL off
Mar 18 01:32:21 n8ntestapp app/web.1 at Parser.parseErrorMessage (/usr/local/lib/node_modules/n8n/node_modules/pg-protocol/dist/parser.js:278:15)
Mar 18 01:32:21 n8ntestapp app/web.1 at Parser.handlePacket (/usr/local/lib/node_modules/n8n/node_modules/pg-protocol/dist/parser.js:126:29)
Mar 18 01:32:21 n8ntestapp app/web.1 at Parser.parse (/usr/local/lib/node_modules/n8n/node_modules/pg-protocol/dist/parser.js:39:38)
Mar 18 01:32:21 n8ntestapp app/web.1 at Socket. (/usr/local/lib/node_modules/n8n/node_modules/pg-protocol/dist/index.js:10:42)
Mar 18 01:32:21 n8ntestapp app/web.1 at Socket.emit (events.js:315:20)
Mar 18 01:32:21 n8ntestapp app/web.1 at addChunk (internal/streams/readable.js:309:12)
Mar 18 01:32:21 n8ntestapp app/web.1 at readableAddChunk (internal/streams/readable.js:284:9)
Mar 18 01:32:21 n8ntestapp app/web.1 at Socket.Readable.push (internal/streams/readable.js:223:10)
Mar 18 01:32:21 n8ntestapp app/web.1 at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Mar 18 01:32:21 n8ntestapp app/web.1 (Use node --trace-warnings ... to show where the warning was created)
Mar 18 01:32:21 n8ntestapp app/web.1 (node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Mar 18 01:32:21 n8ntestapp app/web.1 (node:14) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Mar 18 01:32:23 n8ntestapp app/web.1 (node:14) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
Mar 18 01:32:23 n8ntestapp app/web.1 (node:14) UnhandledPromiseRejectionWarning: Error: There was an error: no pg_hba.conf entry for host "3.249.185.149", user "usr", database "dbdbdb", SSL off
Mar 18 01:32:23 n8ntestapp app/web.1 at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:26:15)
Mar 18 01:32:23 n8ntestapp app/web.1 at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:60:23)
Mar 18 01:32:23 n8ntestapp app/web.1 at /usr/local/lib/node_modules/n8n/dist/commands/start.js:134:22
Mar 18 01:32:23 n8ntestapp app/web.1 (node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Mar 18 01:32:23 n8ntestapp heroku/web.1 Process exited with status 0
Mar 18 01:32:23 n8ntestapp heroku/web.1 State changed from starting to crashed

**Comment by Theguyhere0** [comment]
The issue I found is that a few of the environmental variables weren't added. You'll need to add them yourself by looking inside the app.json and comparing them with the config vars in settings. I got mine to run after changing that. Hope that helps!
